### ISSUE TITLE
Example doesn't work

### ISSUE THREAD

**Issue by nandorojo** [kajchang/react-device-mockups#3]
Hey there, this is the example: https://codesandbox.io/s/sharp-hopper-b5wcj

Note that it just shows an empty iFrame. thanks!

**Comment by kaijchang** [comment]
For me, in the Sandbox, I see the iFrame but no the surrounding iPad. If that's your issue, then I think it might be an issue with CodeSandbox's build.
According to https://create-react-app.dev/docs/adding-images-fonts-and-files,
>webpack finds all relative module references in CSS (they start with ./) and replaces them with the final paths from the compiled bundle.

For some reason, this doesn't seem to work in CodeSandbox:

<img src="https://user-images.githubusercontent.com/39450215/97658656-18aef580-1a2a-11eb-9acd-586bd1fac45a.png" width="250"/>

However, if I download and run what's on CodeSandbox on my computer, it works fine:

<img src="https://user-images.githubusercontent.com/39450215/97658740-5875dd00-1a2a-11eb-9810-d0b59b7da7e1.png" width="250"/>

I'm not exactly sure if there's anything I can do to fix this, but tell me if I'm misunderstanding the issue.
