### ISSUE TITLE
Can i scroll and click on the iframe? 

### ISSUE THREAD

**Issue by msagerup** [kajchang/react-device-mockups#4]
It seems not to work for me

**Comment by msagerup** [comment]
Not possible to interact with the website in the iframe?

**Comment by kaijchang** [comment]
@msagerup Sorry for the late response. Looks like this is from the underlying [html5-device-mockups library](https://github.com/pixelsign/html5-device-mockups). Check out https://github.com/pixelsign/html5-device-mockups/issues/68 for a solution.
